name: Publish dry run

on: [push, pull_request]

jobs:

  publish-dry-run:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Publish dry run
        uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        with:
          credential: ${{ secrets.CREDENTIALS }}
          dry_run: true
